    default_language_version:
      python: python3.12
    default_stages:
      - pre-commit
      - pre-push
    fail_fast: false # Stop running checks after first failure
    repos:
      - repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.5.0
        hooks:
          - id: trailing-whitespace # trims trailing whitespace.
            args: ["--markdown-linebreak-ext=md,markdown"]
          - id: check-case-conflict
          - id: end-of-file-fixer #  ensures that a file is either empty, or ends with one newline.
          - id: mixed-line-ending # replaces or checks mixed line ending.
          - id: requirements-txt-fixer #sorts entries in requirements.txt.
